#include "ActionEncoder.h"
#include "DebugClass.h"
#include "Motor.h"
#include "SlaveBoard.h"

// Heading for manual mode
#include "pinDefind.h"
#include "PS4_serial.h"

//
// Code generated by G Shadow Robot Master
//
// PID
struct position PID_P = {.x = 2.75, .y = 2.75, .w = 2.5};
struct position PID_I = {.x = 0, .y = 0, .w = 0};
struct position PID_D = {.x = 0.75, .y = 0.75, .w = 0};
int maxPointCount = 15;
//
// Code generated by G Shadow Robot Master
//

//Robot components
//DebugClass pc(USBTX, USBRX); //UART_2 (USBTX, USBRX = PA_9, PA_10)
SlaveBoard slave(PA_0, PA_1); //UART_4 for 446 only
ActionEncoder action(PC_10, PC_11); //UART_3
Motor motor;

// Ticker
Ticker motorUpdateTicker;
//Ticker odom_updater;

// Constants
const float UPDATE_RATE = 0.08;//0.08;

// Robot parameters
float lx = INVERSE_KINEMATICS_LX;
float ly = INVERSE_KINEMATICS_LY;
float wheelR = WHEEL_RADIUS; // RoboMaster Mecanum wheel
float gear = GEAR_RATIO;
//float radian_to_rpm_convert = (RAD_TO_DEG / 360) * 60 * gear;
float radian_to_rpm_convert = (1/((2*PI)/60)) * gear * 2;
float r = action.getR();

// Robot Positioning
int targetPoint = 0;
struct pointInfo points[100];
struct position localVelocity, globalVelocity, curPos;
struct position lastError; // For PID_D
struct position targetPos = {
    .x = points[0].targetPos.x,  //  +  startup_offset_x_encoder;
    .y = points[0].targetPos.y,  //  +  startup_offset_y_encoder;
    .w = points[0].targetPos.w * RAD_TO_DEG // -  startup_offset_w_encoder;
};
struct position tolerance = {
    .x = 0.08,
    .y = 0.08,
    .w = 0.1
};
struct position maxSpeed = {
    .x = 1,
    .y = 1,
    .w = 1
};
bool pidOn = points[0].pidOn;
Command command = points[0].command;

// Motor
int motor1 = 0;
int motor2 = 0;
int motor3 = 0;
int motor4 = 0;

// Runtime Parameters
bool autoMode = true;

// Block PS4 button
Timer buttonBlock;
int blockTime = 2000; // Block for 2000 ms
bool firstPress = true;

// manual mode
float joy_range_mid = 128;
float joy_range = 1; //15
float linear_speed = 2;
float angular_speed = 2;
float vt = 0 ;
float vnt = 0 ;
float wt = 0 ;





